title: BloxStreet Support
description: A hub for all things BloxStreet
baseurl: "/"
url: "https://support.bloxstreet.store"

back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

aux_links:
  "Group":
    - "https://group.bloxstreet.store"
  "Store":
    - "https://store.bloxstreet.store"
  "Training Center":
    - "https://www.roblox.com/games/624472608/Training-Center"
  "Quiz Center":
    - "https://www.roblox.com/games/652098479/Quiz-Center"

color_scheme: dark

remote_theme: pmarsceill/just-the-docs
